[tool.poetry]
name = "mikoto.py"
version = "0.0.4"
description = "The Python framework for interacting with Mikoto"
authors = ["TheCactusBlue <cactus@mikoto.io>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "mikoto" }]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.3.0"
python-socketio = "^5.9.0"
httpx = "^0.25.0"
aiohttp = "^3.8.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
